<a href="https://colab.research.google.com/github/MartinTiong/CPE-311/blob/main/Hands_on_Activity_10_1_Data_Analysis_using_Python_TIONG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("bhavikjikadara/mental-health-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'mental-health-dataset' dataset.
Path to dataset files: /kaggle/input/mental-health-dataset

In [6]:
import os
import pandas as pd

# Check files inside dataset
print(os.listdir(path))

['Mental Health Dataset.csv']

In [8]:
df = pd.read_csv('/content/Mental Health Dataset.csv')
df.head()

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,8/27/2014 11:29,Female,United States,Corporate,NaN,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,8/27/2014 11:31,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,8/27/2014 11:32,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
3,8/27/2014 11:37,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes
4,8/27/2014 11:43,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes

3. Prepare the data by applying appropriate data preprocessing techniques.

In [9]:
df.isnull().sum()

df = df.drop_duplicates()

df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce')
df.dtypes

Timestamp                  datetime64[ns]
Gender                             object
Country                            object
Occupation                         object
self_employed                      object
family_history                     object
treatment                          object
Days_Indoors                       object
Growing_Stress                     object
Changes_Habits                     object
Mental_Health_History              object
Mood_Swings                        object
Coping_Struggles                   object
Work_Interest                      object
Social_Weakness                    object
mental_health_interview            object
care_options                       object
dtype: object

4. Analyze the data using descriptive analysis.

It shows that the dataset contains about 290,000 responses with 17 variables related to mental health. Most respondents were male and not self employed. Many individuals reported experiencing growing stress, mood swings, and coping struggles.

5. Perform correlation analysis.

In [12]:
df_encoded = df.copy()

for col in df_encoded.select_dtypes(include=['object']).columns:
    df_encoded[col] = df_encoded[col].astype('category').cat.codes

correlation_matrix = df_encoded.corr()

correlation_matrix

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
Timestamp,1.000000,0.006566,-0.049776,-0.000146,0.001435,0.064276,0.084747,-0.000136,-0.000361,0.000022,0.000183,0.000120,-0.000377,-0.000129,-0.000063,0.021728,0.054860
Gender,0.006566,1.000000,-0.033654,-0.022207,0.069423,-0.199641,-0.178129,-0.020765,-0.054931,0.003310,0.027879,0.018338,-0.057436,-0.019593,-0.009595,-0.071014,-0.106815
Country,-0.049776,-0.033654,1.000000,0.000747,-0.115587,0.031439,0.062004,0.000699,0.001849,-0.000111,-0.000938,-0.000617,0.001933,0.000659,0.000323,0.024218,0.023322
Occupation,-0.000146,-0.022207,0.000747,1.000000,-0.001542,0.004433,0.003956,-0.006823,-0.050309,0.019726,-0.004552,-0.149133,0.013567,-0.016139,-0.046950,0.001577,0.002372
self_employed,0.001435,0.069423,-0.115587,-0.001542,1.000000,0.010478,0.027897,-0.001442,-0.003813,0.000230,0.001935,0.001273,-0.003987,-0.001360,-0.000666,-0.037537,0.047447
family_history,0.064276,-0.199641,0.031439,0.004433,0.010478,1.000000,0.364737,0.004145,0.010966,-0.000661,-0.005566,-0.003661,0.011467,0.003912,0.001916,0.024430,0.124208
treatment,0.084747,-0.178129,0.062004,0.003956,0.027897,0.364737,1.000000,0.003699,0.009785,-0.000590,-0.004966,-0.003267,0.010231,0.003490,0.001709,0.091964,0.250555
Days_Indoors,-0.000136,-0.020765,0.000699,-0.006823,-0.001442,0.004145,0.003699,1.000000,-0.033954,0.000832,-0.035933,-0.015407,0.067612,-0.021344,-0.061067,0.001475,0.002218
Growing_Stress,-0.000361,-0.054931,0.001849,-0.050309,-0.003813,0.010966,0.009785,-0.033954,1.000000,-0.073424,0.005849,0.044700,0.021343,-0.006564,0.020539,0.003901,0.005867
Changes_Habits,0.000022,0.003310,-0.000111,0.019726,0.000230,-0.000661,-0.000590,0.000832,-0.073424,1.000000,0.056352,0.075045,0.021941,0.015432,0.000556,-0.000235,-0.000354
Mental_Health_History,0.000183,0.027879,-0.000938,-0.004552,0.001935,-0.005566,-0.004966,-0.035933,0.005849,0.056352,1.000000,0.054670,0.031456,0.009197,0.016243,-0.001980,-0.002978
Mood_Swings,0.000120,0.018338,-0.000617,-0.149133,0.001273,-0.003661,-0.003267,-0.015407,0.044700,0.075045,0.054670,1.000000,-0.029461,-0.060351,0.031437,-0.001302,-0.001959
Coping_Struggles,-0.000377,-0.057436,0.001933,0.013567,-0.003987,0.011467,0.010231,0.067612,0.021343,0.021941,0.031456,-0.029461,1.000000,-0.012675,0.028635,0.004079,0.006135
Work_Interest,-0.000129,-0.019593,0.000659,-0.016139,-0.001360,0.003912,0.003490,-0.021344,-0.006564,0.015432,0.009197,-0.060351,-0.012675,1.000000,-0.042837,0.001391,0.002093
Social_Weakness,-0.000063,-0.009595,0.000323,-0.046950,-0.000666,0.001916,0.001709,-0.061067,0.020539,0.000556,0.016243,0.031437,0.028635,-0.042837,1.000000,0.000681,0.001025
mental_health_interview,0.021728,-0.071014,0.024218,0.001577,-0.037537,0.024430,0.091964,0.001475,0.003901,-0.000235,-0.001980,-0.001302,0.004079,0.001391,0.000681,1.000000,-0.002805
care_options,0.054860,-0.106815,0.023322,0.002372,0.047447,0.124208,0.250555,0.002218,0.005867,-0.000354,-0.002978,-0.001959,0.006135,0.002093,0.001025,-0.002805,1.000000

6. Interpret the results based on the descriptive and correlation analysis.

The correlation analysis showed that therea re several relationships between variables. Individuals with a family history of mental illness were more likely to seek treatment. Growing stress showed a positive relationship with mood swings, suggesting that higher stress levels affect emotional stability. Coping struggles were negatively related to work interest, indicating that mental health challenges may reduce productivity.